name: form_bloc
description: Easy Form State Management using BLoC pattern. Separate the Form State and Business Logic from the User Interface. Async Validation, Progress, Dynamic fields, and more.
version: 0.19.1
homepage: https://github.com/GiancarloCode/form_bloc/tree/master/packages/form_bloc
repository: https://github.com/GiancarloCode/form_bloc/tree/master/packages/form_bloc
issue_tracker: https://github.com/GiancarloCode/form_bloc/issues

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  meta: ^1.1.6
  bloc: ^6.0.0
  bloc_test: ^7.0.0
  rxdart: ^0.24.1
  equatable: ^2.0.0
  quiver: ^3.0.0
  mockito: ^4.1.1
  pedantic: ^1.8.0+1
  collection: ^1.14.11
  uuid: ^3.0.0

dev_dependencies:
  test: ^1.6.0
